AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  vikingosSpikesTerraformLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: co.vikingos.spikes.aws.BookRequestHandler
      Runtime: java11
      CodeUri: './code/'
      MemorySize: 512
      Timeout: 30